import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Memulai seeding database...");

  // --- Users ---
  const superAdminPassword = await bcrypt.hash("PrimeSuperSecure2026!", 10);
  const adminPassword = await bcrypt.hash("PrimeAdminAccess2026!", 10);

  const superAdmin = await prisma.user.upsert({
    where: { email: "super@primeproperty.id" },
    update: {},
    create: {
      email: "super@primeproperty.id",
      password: superAdminPassword,
      name: "Super Admin",
      role: "SUPERADMIN",
      isActive: true,
    },
  });

  const admin = await prisma.user.upsert({
    where: { email: "admin@primeproperty.id" },
    update: {},
    create: {
      email: "admin@primeproperty.id",
      password: adminPassword,
      name: "Admin User",
      role: "ADMIN",
      isActive: true,
    },
  });

  console.log(`✅ User dibuat: ${superAdmin.name}, ${admin.name}`);

  // --- Properties ---
  const properties: Array<{
    namaProperty: string;
    group: string | null;
    lebar: number;
    panjang: number;
    hadap: string;
    tipe: string;
    tingkat: number;
    price: bigint;
    carport: boolean;
    status: string;
    siap: string;
    mapsLink: string | null;
    kawasan: string;
    unit: string | null;
  }> = [
    {
      namaProperty: "Aston Villas",
      group: "Mentari",
      lebar: 8,
      panjang: 18,
      hadap: JSON.stringify(["Utara"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(2_850_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5952,98.6722",
      kawasan: JSON.stringify(["Krakatau"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Banyan Tree Blok A",
      group: "Permai 123",
      lebar: 6,
      panjang: 15,
      hadap: JSON.stringify(["Selatan"]),
      tipe: "RUKO",
      tingkat: 3,
      price: BigInt(1_750_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: "https://maps.google.com/?q=3.5871,98.6890",
      kawasan: JSON.stringify(["Pancing"]),
      unit: null,
    },
    {
      namaProperty: "Griya Mentari",
      group: "Mentari",
      lebar: 7,
      panjang: 16,
      hadap: JSON.stringify(["Timur"]),
      tipe: "VILLA",
      tingkat: 1,
      price: BigInt(1_200_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: null,
      kawasan: JSON.stringify(["Tembung"]),
      unit: null,
    },
    {
      namaProperty: "Puri Indah Residence",
      group: "Project Ville",
      lebar: 10,
      panjang: 20,
      hadap: JSON.stringify(["Utara", "Barat"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(3_500_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.6102,98.6500",
      kawasan: JSON.stringify(["Helvetia"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Green Valley Blok B",
      group: "Green Valley",
      lebar: 5,
      panjang: 12,
      hadap: JSON.stringify(["Barat"]),
      tipe: "RUKO",
      tingkat: 2,
      price: BigInt(980_000_000),
      carport: false,
      status: "SOLD_OUT",
      siap: "SIAP_HUNI",
      mapsLink: null,
      kawasan: JSON.stringify(["Cemara Asri"]),
      unit: null,
    },
    {
      namaProperty: "Golden Gate Tower",
      group: "Golden Gate",
      lebar: 4.5,
      panjang: 14,
      hadap: JSON.stringify(["Selatan", "Timur"]),
      tipe: "RUKO",
      tingkat: 3.5,
      price: BigInt(2_100_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: "https://maps.google.com/?q=3.5750,98.7010",
      kawasan: JSON.stringify(["Sunggal"]),
      unit: "Gate siap",
    },
    {
      namaProperty: "Cemara Heights",
      group: "Permai 123",
      lebar: 9,
      panjang: 22,
      hadap: JSON.stringify(["Utara"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(4_200_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5820,98.6650",
      kawasan: JSON.stringify(["Cemara Asri"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Ruko Krakatau Square",
      group: null,
      lebar: 4,
      panjang: 12,
      hadap: JSON.stringify(["Timur"]),
      tipe: "RUKO",
      tingkat: 2,
      price: BigInt(850_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: null,
      kawasan: JSON.stringify(["Krakatau"]),
      unit: null,
    },
    {
      namaProperty: "Villa Pancing Asri",
      group: "Mentari",
      lebar: 8,
      panjang: 20,
      hadap: JSON.stringify(["Barat"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(2_600_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI_RENOVASI",
      mapsLink: "https://maps.google.com/?q=3.5900,98.6870",
      kawasan: JSON.stringify(["Pancing"]),
      unit: null,
    },
    {
      namaProperty: "Taman Helvetia Blok C",
      group: "Green Valley",
      lebar: 6,
      panjang: 15,
      hadap: JSON.stringify(["Utara", "Timur"]),
      tipe: "VILLA",
      tingkat: 1.5,
      price: BigInt(1_350_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: null,
      kawasan: JSON.stringify(["Helvetia"]),
      unit: null,
    },
    {
      namaProperty: "Ruko Sunggal Trade Center",
      group: "Golden Gate",
      lebar: 5,
      panjang: 18,
      hadap: JSON.stringify(["Selatan"]),
      tipe: "RUKO",
      tingkat: 3,
      price: BigInt(1_900_000_000),
      carport: false,
      status: "SOLD_OUT",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5680,98.6430",
      kawasan: JSON.stringify(["Sunggal"]),
      unit: null,
    },
    {
      namaProperty: "Graha Marelan",
      group: "Project Ville",
      lebar: 7,
      panjang: 16,
      hadap: JSON.stringify(["Barat"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(1_650_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: null,
      kawasan: JSON.stringify(["Marelan"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Amplas Business Park",
      group: null,
      lebar: 4.5,
      panjang: 14,
      hadap: JSON.stringify(["Timur"]),
      tipe: "RUKO",
      tingkat: 2.5,
      price: BigInt(1_100_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: "https://maps.google.com/?q=3.5450,98.7100",
      kawasan: JSON.stringify(["Amplas"]),
      unit: null,
    },
    {
      namaProperty: "Johor Residence Premium",
      group: "Permai 123",
      lebar: 10,
      panjang: 25,
      hadap: JSON.stringify(["Utara", "Barat"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(5_000_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5550,98.6780",
      kawasan: JSON.stringify(["Johor"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Medan Kota Center",
      group: "Golden Gate",
      lebar: 4,
      panjang: 10,
      hadap: JSON.stringify(["Selatan"]),
      tipe: "RUKO",
      tingkat: 4,
      price: BigInt(3_200_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: "https://maps.google.com/?q=3.5952,98.6722",
      kawasan: JSON.stringify(["Medan Kota"]),
      unit: "Gate siap",
    },
    {
      namaProperty: "Villa Tembung Indah",
      group: "Mentari",
      lebar: 7,
      panjang: 17,
      hadap: JSON.stringify(["Timur", "Selatan"]),
      tipe: "VILLA",
      tingkat: 1,
      price: BigInt(950_000_000),
      carport: true,
      status: "SOLD_OUT",
      siap: "SIAP_HUNI",
      mapsLink: null,
      kawasan: JSON.stringify(["Tembung"]),
      unit: null,
    },
    {
      namaProperty: "Permai Garden",
      group: "Permai 123",
      lebar: 8,
      panjang: 19,
      hadap: JSON.stringify(["Utara"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(2_400_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.6000,98.6550",
      kawasan: JSON.stringify(["Krakatau", "Pancing"]),
      unit: null,
    },
    {
      namaProperty: "Ruko Cemara Jaya",
      group: "Green Valley",
      lebar: 5,
      panjang: 13,
      hadap: JSON.stringify(["Barat"]),
      tipe: "RUKO",
      tingkat: 2,
      price: BigInt(780_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: null,
      kawasan: JSON.stringify(["Cemara Asri"]),
      unit: null,
    },
    {
      namaProperty: "Helvetia Grand Villa",
      group: "Project Ville",
      lebar: 10,
      panjang: 22,
      hadap: JSON.stringify(["Utara", "Timur"]),
      tipe: "VILLA",
      tingkat: 2.5,
      price: BigInt(4_500_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.6100,98.6480",
      kawasan: JSON.stringify(["Helvetia"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Ruko Marelan Baru",
      group: null,
      lebar: 4,
      panjang: 11,
      hadap: JSON.stringify(["Selatan"]),
      tipe: "RUKO",
      tingkat: 2,
      price: BigInt(620_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: null,
      kawasan: JSON.stringify(["Marelan"]),
      unit: null,
    },
    {
      namaProperty: "Sunggal Prestige",
      group: "Golden Gate",
      lebar: 9,
      panjang: 20,
      hadap: JSON.stringify(["Barat", "Utara"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(3_100_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5700,98.6400",
      kawasan: JSON.stringify(["Sunggal"]),
      unit: null,
    },
    {
      namaProperty: "Amplas Green Residence",
      group: "Green Valley",
      lebar: 6,
      panjang: 16,
      hadap: JSON.stringify(["Timur"]),
      tipe: "VILLA",
      tingkat: 1,
      price: BigInt(1_050_000_000),
      carport: true,
      status: "SOLD_OUT",
      siap: "SIAP_HUNI",
      mapsLink: null,
      kawasan: JSON.stringify(["Amplas"]),
      unit: null,
    },
    {
      namaProperty: "Ruko Johor Plaza",
      group: "Permai 123",
      lebar: 5,
      panjang: 15,
      hadap: JSON.stringify(["Selatan", "Barat"]),
      tipe: "RUKO",
      tingkat: 3,
      price: BigInt(1_800_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: "https://maps.google.com/?q=3.5530,98.6800",
      kawasan: JSON.stringify(["Johor"]),
      unit: "Gate siap",
    },
    {
      namaProperty: "Villa Krakatau Permai",
      group: "Mentari",
      lebar: 8,
      panjang: 18,
      hadap: JSON.stringify(["Utara"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(2_750_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5960,98.6730",
      kawasan: JSON.stringify(["Krakatau"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Medan Kota Square",
      group: "Golden Gate",
      lebar: 4.5,
      panjang: 12,
      hadap: JSON.stringify(["Timur"]),
      tipe: "RUKO",
      tingkat: 3,
      price: BigInt(2_500_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: "https://maps.google.com/?q=3.5940,98.6740",
      kawasan: JSON.stringify(["Medan Kota"]),
      unit: null,
    },
    {
      namaProperty: "Taman Pancing Indah",
      group: "Project Ville",
      lebar: 7,
      panjang: 17,
      hadap: JSON.stringify(["Barat"]),
      tipe: "VILLA",
      tingkat: 1.5,
      price: BigInt(1_500_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI_RENOVASI",
      mapsLink: null,
      kawasan: JSON.stringify(["Pancing"]),
      unit: null,
    },
    {
      namaProperty: "Griya Tembung Asri",
      group: "Green Valley",
      lebar: 6,
      panjang: 14,
      hadap: JSON.stringify(["Selatan"]),
      tipe: "VILLA",
      tingkat: 1,
      price: BigInt(880_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: null,
      kawasan: JSON.stringify(["Tembung"]),
      unit: null,
    },
    {
      namaProperty: "Ruko Helvetia Raya",
      group: null,
      lebar: 5,
      panjang: 16,
      hadap: JSON.stringify(["Utara", "Selatan"]),
      tipe: "RUKO",
      tingkat: 2.5,
      price: BigInt(1_350_000_000),
      carport: false,
      status: "SOLD_OUT",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.6080,98.6510",
      kawasan: JSON.stringify(["Helvetia"]),
      unit: null,
    },
    {
      namaProperty: "Cemara Asri Grand",
      group: "Permai 123",
      lebar: 10,
      panjang: 24,
      hadap: JSON.stringify(["Timur", "Utara"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(4_800_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.6200,98.6350",
      kawasan: JSON.stringify(["Cemara Asri"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Ruko Sunggal Corner",
      group: "Golden Gate",
      lebar: 4,
      panjang: 10,
      hadap: JSON.stringify(["Barat"]),
      tipe: "RUKO",
      tingkat: 2,
      price: BigInt(720_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: null,
      kawasan: JSON.stringify(["Sunggal"]),
      unit: null,
    },
    {
      namaProperty: "Marelan City Villa",
      group: "Project Ville",
      lebar: 8,
      panjang: 19,
      hadap: JSON.stringify(["Utara"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(2_200_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.7100,98.6300",
      kawasan: JSON.stringify(["Marelan"]),
      unit: null,
    },
    {
      namaProperty: "Ruko Amplas Megah",
      group: null,
      lebar: 5,
      panjang: 14,
      hadap: JSON.stringify(["Selatan", "Timur"]),
      tipe: "RUKO",
      tingkat: 3,
      price: BigInt(1_400_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: "https://maps.google.com/?q=3.5400,98.7120",
      kawasan: JSON.stringify(["Amplas"]),
      unit: "Gate siap",
    },
    {
      namaProperty: "Johor Valley Estate",
      group: "Mentari",
      lebar: 9,
      panjang: 22,
      hadap: JSON.stringify(["Barat", "Selatan"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(3_800_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5520,98.6820",
      kawasan: JSON.stringify(["Johor"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Krakatau Shophouse",
      group: "Permai 123",
      lebar: 4.5,
      panjang: 13,
      hadap: JSON.stringify(["Utara"]),
      tipe: "RUKO",
      tingkat: 2,
      price: BigInt(900_000_000),
      carport: false,
      status: "SOLD_OUT",
      siap: "SIAP_HUNI",
      mapsLink: null,
      kawasan: JSON.stringify(["Krakatau"]),
      unit: null,
    },
    {
      namaProperty: "Medan Kota Residence",
      group: "Golden Gate",
      lebar: 7,
      panjang: 18,
      hadap: JSON.stringify(["Timur"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(3_400_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5950,98.6710",
      kawasan: JSON.stringify(["Medan Kota"]),
      unit: null,
    },
    {
      namaProperty: "Pancing Trade Mall",
      group: null,
      lebar: 6,
      panjang: 16,
      hadap: JSON.stringify(["Selatan"]),
      tipe: "RUKO",
      tingkat: 3.5,
      price: BigInt(2_000_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: "https://maps.google.com/?q=3.5880,98.6900",
      kawasan: JSON.stringify(["Pancing"]),
      unit: null,
    },
    {
      namaProperty: "Villa Cemara Elok",
      group: "Green Valley",
      lebar: 8,
      panjang: 20,
      hadap: JSON.stringify(["Barat", "Utara"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(2_950_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: null,
      kawasan: JSON.stringify(["Cemara Asri"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Tembung Commerce",
      group: "Project Ville",
      lebar: 4,
      panjang: 11,
      hadap: JSON.stringify(["Timur"]),
      tipe: "RUKO",
      tingkat: 2,
      price: BigInt(650_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: null,
      kawasan: JSON.stringify(["Tembung"]),
      unit: null,
    },
    {
      namaProperty: "Helvetia Park Villa",
      group: "Mentari",
      lebar: 9,
      panjang: 21,
      hadap: JSON.stringify(["Utara", "Barat"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(3_700_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.6120,98.6490",
      kawasan: JSON.stringify(["Helvetia"]),
      unit: null,
    },
    {
      namaProperty: "Ruko Krakatau Timur",
      group: "Permai 123",
      lebar: 5,
      panjang: 15,
      hadap: JSON.stringify(["Selatan"]),
      tipe: "RUKO",
      tingkat: 2.5,
      price: BigInt(1_150_000_000),
      carport: false,
      status: "SOLD_OUT",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5970,98.6750",
      kawasan: JSON.stringify(["Krakatau"]),
      unit: null,
    },
    {
      namaProperty: "Sunggal Lake View",
      group: "Green Valley",
      lebar: 10,
      panjang: 23,
      hadap: JSON.stringify(["Barat"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(4_100_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5720,98.6380",
      kawasan: JSON.stringify(["Sunggal"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Marelan Corner Shop",
      group: null,
      lebar: 4,
      panjang: 12,
      hadap: JSON.stringify(["Timur", "Selatan"]),
      tipe: "RUKO",
      tingkat: 2,
      price: BigInt(580_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: null,
      kawasan: JSON.stringify(["Marelan"]),
      unit: null,
    },
    {
      namaProperty: "Amplas Heritage",
      group: "Project Ville",
      lebar: 7,
      panjang: 17,
      hadap: JSON.stringify(["Utara"]),
      tipe: "VILLA",
      tingkat: 1.5,
      price: BigInt(1_280_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI_RENOVASI",
      mapsLink: null,
      kawasan: JSON.stringify(["Amplas"]),
      unit: null,
    },
    {
      namaProperty: "Johor Central Ruko",
      group: "Golden Gate",
      lebar: 5,
      panjang: 14,
      hadap: JSON.stringify(["Barat"]),
      tipe: "RUKO",
      tingkat: 3,
      price: BigInt(1_680_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: "https://maps.google.com/?q=3.5540,98.6790",
      kawasan: JSON.stringify(["Johor"]),
      unit: "Gate siap",
    },
    {
      namaProperty: "Medan Kota Premiere",
      group: "Permai 123",
      lebar: 9,
      panjang: 20,
      hadap: JSON.stringify(["Selatan", "Timur"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(4_600_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5960,98.6700",
      kawasan: JSON.stringify(["Medan Kota"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Pancing Riverside",
      group: "Mentari",
      lebar: 8,
      panjang: 18,
      hadap: JSON.stringify(["Utara"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(2_300_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5890,98.6880",
      kawasan: JSON.stringify(["Pancing"]),
      unit: null,
    },
    {
      namaProperty: "Ruko Tembung Jaya",
      group: null,
      lebar: 4.5,
      panjang: 13,
      hadap: JSON.stringify(["Barat", "Selatan"]),
      tipe: "RUKO",
      tingkat: 2,
      price: BigInt(750_000_000),
      carport: false,
      status: "SOLD_OUT",
      siap: "SIAP_HUNI",
      mapsLink: null,
      kawasan: JSON.stringify(["Tembung"]),
      unit: null,
    },
    {
      namaProperty: "Cemara Asri Boulevard",
      group: "Green Valley",
      lebar: 10,
      panjang: 25,
      hadap: JSON.stringify(["Timur"]),
      tipe: "VILLA",
      tingkat: 2.5,
      price: BigInt(4_900_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.6210,98.6340",
      kawasan: JSON.stringify(["Cemara Asri"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Helvetia Business Hub",
      group: "Golden Gate",
      lebar: 5,
      panjang: 15,
      hadap: JSON.stringify(["Selatan"]),
      tipe: "RUKO",
      tingkat: 3,
      price: BigInt(1_950_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: "https://maps.google.com/?q=3.6090,98.6520",
      kawasan: JSON.stringify(["Helvetia"]),
      unit: null,
    },
    {
      namaProperty: "Krakatau Mansion",
      group: "Mentari",
      lebar: 10,
      panjang: 22,
      hadap: JSON.stringify(["Utara", "Barat"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(4_300_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI",
      mapsLink: "https://maps.google.com/?q=3.5955,98.6725",
      kawasan: JSON.stringify(["Krakatau"]),
      unit: "Ready Siap huni",
    },
    {
      namaProperty: "Ruko Pancing Utara",
      group: "Project Ville",
      lebar: 4,
      panjang: 11,
      hadap: JSON.stringify(["Timur"]),
      tipe: "RUKO",
      tingkat: 2,
      price: BigInt(680_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: null,
      kawasan: JSON.stringify(["Pancing"]),
      unit: null,
    },
    {
      namaProperty: "Sunggal Harmony Villa",
      group: "Permai 123",
      lebar: 8,
      panjang: 19,
      hadap: JSON.stringify(["Barat"]),
      tipe: "VILLA",
      tingkat: 2,
      price: BigInt(2_700_000_000),
      carport: true,
      status: "IN_STOCK",
      siap: "SIAP_HUNI_RENOVASI",
      mapsLink: "https://maps.google.com/?q=3.5710,98.6410",
      kawasan: JSON.stringify(["Sunggal"]),
      unit: null,
    },
    {
      namaProperty: "Marelan Regency",
      group: "Green Valley",
      lebar: 7,
      panjang: 17,
      hadap: JSON.stringify(["Selatan", "Utara"]),
      tipe: "VILLA",
      tingkat: 1.5,
      price: BigInt(1_450_000_000),
      carport: true,
      status: "SOLD_OUT",
      siap: "SIAP_HUNI",
      mapsLink: null,
      kawasan: JSON.stringify(["Marelan"]),
      unit: null,
    },
    {
      namaProperty: "Amplas Trade Center",
      group: "Golden Gate",
      lebar: 5,
      panjang: 16,
      hadap: JSON.stringify(["Timur", "Barat"]),
      tipe: "RUKO",
      tingkat: 3.5,
      price: BigInt(1_550_000_000),
      carport: false,
      status: "IN_STOCK",
      siap: "SIAP_KOSONG",
      mapsLink: "https://maps.google.com/?q=3.5430,98.7110",
      kawasan: JSON.stringify(["Amplas"]),
      unit: "Gate siap",
    },
  ];

  console.log(`📦 Membuat ${properties.length} properti...`);

  for (const property of properties) {
    await prisma.property.create({
      data: {
        ...property,
        createdById: superAdmin.id,
      },
    });
  }

  console.log(`✅ ${properties.length} properti berhasil dibuat`);
  console.log("🎉 Seeding selesai!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding gagal:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
